#!/bin/sh

# mount -t devtmpfs devtmpfs /dev << happens automatically with devtmpfs, so we don't need to do it manually
mount -t proc proc /proc
mount -t sysfs sysfs /sys
mount -t tmpfs tmpfs /tmp
echo "System booted successfully!"
